---
# Default configuration for ComptoxAI
neo4j:
  username: neo4j
  password: neo4j
  hostname: localhost
  protocol: bolt
  port: 7687

mysql:
  user:
  passwd:
  host:

data:
  prefix: D:\data\
  tempdir: D:\data\comptox_ai\

...