---
# This Conda environment solves the dependencies needed for GPU support
# in ComptoxAI. If you can't (or don't want to) use CUDA 10.2, installing
# ComptoxAI using setuptools will be good enough to get you up and running.
#
# To use:
#
#   $ conda env create -f environment.yml
#   $ conda activate comptox_ai

name: comptox_ai
channels:
  - anaconda
  - conda-forge
  - nvidia
  - pytorch
  - dglteam
dependencies:
  - ablog=0.10.19
  - nvidia::cudatoolkit=11.1
  - mysqlclient=2.0.3
  - networkx=2.6.3
  - neo4j-python-driver=4.3.4
  - numpy
  - openpyxl=3.0.8
  - owlready2=0.34
  - pandas
  - pytest=6.2.5
  - python=3.8
  - pytorch::pytorch
  - pyyaml=5.4.1
  - rdflib=5.0.0
  - scipy=1.7.1
  - tqdm=4.62.2
  - conda-forge::molfeat
  - conda-forge::rdkit
  - conda-forge::ipdb
  - transformers
  - dglteam:dgl=2.0.0
  - conda-forge::dgllife
