---
# Automates building and testing of a Python package
name: ci-python-package

# Define the events that trigger the workflow
on:
  push:
    branches:
      - [$default-branch]
  workflow_dispatch:

# Define the jobs in the workflow
jobs:
  build-package:
    # Define the type of runner to use
    runs-on: ubuntu-latest

    # Define strategy for matrix builds
    strategy:
      matrix:
        # You can change the default value as needed
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      # Step: Check out the repository's code to the runner
      - name: checkout-code
        uses: actions/checkout@v3

      # Step: Set up Python environment
      - name: setup-python-env ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step: Install project dependencies using pip
      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .
      #
      # Step: Run pip test
      - name: run-test
        run: pip test
