---
name: ci-python-test

# Define the events that trigger the workflow
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

# Define the jobs in the workflow
jobs:
  python-test:
    # Define the type of runner to use
    runs-on: ubuntu-latest

    # Define strategy for matrix builds
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']

    steps:
      # Step: Check out the repository's code to the runner
      - name: checkout-code
        uses: actions/checkout@v3

      # Step: Set up Python environment
      - name: setup-python-env ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step: Install project dependencies
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
      

      # Step: Run tests with Pytest
      - name: run-tests
        run: |
          $CONDA/bin/pytest
